import anthropic
import json
import os
import re

from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(__file__), '..', '.env'))

client = anthropic.Anthropic()


def generate_explanation(
    input_text, classification, confidence,
    retrieved_evidence, method_used, context_type
):
    """Generate an explainable AI justification using only retrieved RAG context.

    Every explanation is generated by Claude using retrieved evidence —
    not templated text. This ensures full transparency and auditability.

    Args:
        input_text:          The original text being classified.
        classification:      The AI classification result (e.g. 'GAP_DETECTED', 'OK').
        confidence:          Confidence score (0.0–1.0).
        retrieved_evidence:  List of dicts with 'source_type', 'source_document', 'content'.
        method_used:         Classification method (e.g. 'RAG+Claude', 'keyword', 'embedding').
        context_type:        Type of input (e.g. 'clinical_note', 'patient_review').

    Returns:
        dict with structured explanation fields.
    """
    evidence_text = "\n".join([
        f"[{e['source_type']} from {e['source_document']}]: "
        f"{e['content'][:200]}"
        for e in retrieved_evidence
    ])

    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=800,
        system="""You are an explainable AI for public \
health analysts. Justify every classification \
using only the retrieved evidence provided. \
Never add medical knowledge beyond what is \
in the retrieved evidence. Be transparent \
about uncertainty.""",
        messages=[{"role": "user", "content": f"""
Explain this AI classification:

Input (anonymized): {input_text[:300]}
Classification: {classification}
Confidence: {confidence:.0%}
Method: {method_used}

Retrieved evidence from knowledge base:
{evidence_text}

Return ONLY JSON:
{{
  "summary_for_analyst": "2-3 plain English sentences for public health official. Reference specific evidence retrieved.",
  "evidence_used": ["evidence item 1", "evidence item 2"],
  "confidence_justification": "based on retrieved evidence",
  "uncertainty_flags": ["what is uncertain"],
  "recommended_action": "what analyst should do",
  "ethical_confirmation": {{
    "individual_identified": false,
    "population_level_only": true,
    "human_review_required": true,
    "data_source": "public anonymized sources only",
    "statement": "No individual identified. Population-level insight only. Human review required."
  }}
}}"""}]
    )

    text = response.content[0].text
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        # strip markdown fences if present
        cleaned = re.sub(r'```json|```', '', text).strip()
        return json.loads(cleaned)
